### ISSUE TITLE
TWA keeps opening notification "Running in Chrome"

### ISSUE THREAD

**Issue by Vegas10128** [GoogleChrome/android-browser-helper#172]
Anytime user accesses the app by the following. 
- Tap the launcher Icon
- Opens TWA in tasks

Notification opens at the top of screen. 
"Running in Chrome" 

User cannot touch "Got It" and presenting annoyance as it shows every time the app is opened. 

Bug issue found under TWA Multi Domain. 
Tested on physical device, LG Stylo 5.

**Comment by PEConn** [comment]
Hey, if you open the TWA a second time, does the notification still appear (subsequent launches should have a low priority notification that isn't intrusive to the user), also if you dismiss it by swiping away, does it go away/stay away?

**Comment by PEConn** [comment]
Bug is being tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=1126040

**Comment by Vegas10128** [comment]
Hello PEConn!
Sorry for late reply, i was not expecting anyone to get back so quickly!
Yes it is every time i open TWA app the notification appears, "Got it" button does not work, and you have to swipe. 
Also appears in task notifications bar, and "Got it" button does not work either. User has to swipe the notification from the task bar as well. 
Thank you for the buck tracker report! I will definitely keep an eye on this.

**Comment by andreban** [comment]
Closing as the underlying bug in Chrome was fixed.

**Comment by AlissonRS** [comment]
Hi @andreban 

Do you have any idea when they are planning to release this fix for Chrome?

As of now I'm still getting this notification every time I open my TWA, so I'm guessing they didn't release yet.

I'm currently using Chrome Version 87.0.4280.101 in my smartphone.

**Comment by AlissonRS** [comment]
Quick update:

Actually it happens when you first install the TWA from Google Play. It'll show the notification every time you open the app, it only stops if you hard close the app.

https://bugs.chromium.org/p/chromium/issues/detail?id=981323

**Comment by PEConn** [comment]
The bug you linked was about something different - it's about being able to customize the notification displayed.

[This bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1126040) is about the notification not being dismissable.

It's concerning that you're still seeing the issue - it should have been fixed from 87.0.4259.0.

Are you totally sure that the TWA is running in that version of Chrome (maybe you have Chrome Stable and Chrome Beta installed, you're checking the version for Beta but Stable is the default?). Could you try with Chrome Dev or Chrome Canary?

**Comment by AlissonRS** [comment]
@PEConn thanks for your reply.

You're right the bug I linked is about customizing it, but if you read recent comments, specifically one at "Wed, Oct 28, 2020, 8:06 PM GMT", it says this:

> I just checked and the current toast is still broken. It still spams the user with the toast an unlimited number of times, once for every time they switch back to the app, and it doesn't stop until you hard-close the app and re-open it. The "Got It" button also is not clickable and does nothing.

This is reproducible. go to Google Play Store, download some TWA like "Imgflip" (it's not my app, but they have the same issue), after you install it, the first time you open it shows the toast. Go to home page or switch to any other app without closing Imgflip. Now go back to Imgflip, the toast will be displayed again.

The toast is only gone after you hard-close the app in your phone.

I'm not using Chrome Beta, and I reproduced this issue in other smartphones too.

**Comment by AlissonRS** [comment]
@PEConn for reference, I opened a new bug on chromium, and I even attached a video demonstrating the issue. I don't think there is anything wrong on android-browser-helper, so this issue can be kept closed, just wanted to share the bug link if anyone ended up here.

https://bugs.chromium.org/p/chromium/issues/detail?id=1168307

**Comment by andreban** [comment]
Just to close the loop in this thread. This seems to be the same as https://bugs.chromium.org/p/chromium/issues/detail?id=1136477, which should be fixed in Chrome 88, which was released this week.
